"""Regenerate the private decimal power cache using exact integer arithmetic."""
from pathlib import Path

lines = [
    "# Generated by tools/generate_float_powers.py; do not edit.",
    "# floor(10^q / 2^exponent), normalized to 128 bits.",
    "const FloatPowers: array[-342..308, tuple[hi, lo: uint64, exponent: int]] = [",
]
for q in range(-342, 309):
    numerator, denominator = (10**q, 1) if q >= 0 else (1, 10**-q)
    binary = numerator.bit_length() - denominator.bit_length()
    if binary >= 0:
        binary -= numerator < (denominator << binary)
    else:
        binary -= (numerator << -binary) < denominator
    exponent = binary - 127
    if exponent >= 0:
        a, b = numerator, denominator << exponent
    else:
        a, b = numerator << -exponent, denominator
    power = a // b
    assert 2**127 <= power < 2**128
    assert power * b <= a < (power + 1) * b
    lines.append(
        f"  (0x{power >> 64:016x}'u64, 0x{power % (2**64):016x}'u64, {exponent}), # {q}"
    )
lines.append("]")
root = Path(__file__).resolve().parent.parent
(root / "src/brian_float_powers.nim").write_text("\n".join(lines) + "\n")
